### ISSUE TITLE
about genericxlog in rum

### ISSUE THREAD

**Issue by joseph-zh** [postgrespro/rum#46]
Hello:

I have a question to ask.
RUM index is a extension for PostgreSQL，so it only can use Generic Xlog to write wal.
I want to put RUM into PG,As part of postgres porcess. so I want to change the the wal's mode,not use Generic xlog. I imitate GIN index to write RUM's wal process,but I have many difficulty to finish it.
so , I want to know do you have any details infomation about rum index wal, because gin and rum has some different in coding.

ths very much.

joseph long

**Comment by akorotkov** [comment]
Hi, Joseph!

Right, generic WAL is very inefficient when data on the page is shifted.  All the shifted part is assumed to be different between page versions.  But we have pending patch, which implementing compression of generic WAL.  This patch implements alignment, which can successfully detect data shift.  See this thread: https://www.postgresql.org/message-id/flat/59F90ABF.2060407%40postgrespro.ru
I also would like to know exact purpose of your work.  Are you going to push RUM to PostgreSQL community?  Or add it to your own fork or PostgreSQL?  Or your problem is just inefficient generic WAL?

**Comment by joseph-zh** [comment]
hi, akorotkov:

I want add rum to my own fork. 
the patch you provided I have used before. the insertion is slower. So I want to ask, did you have any suggestion to improve the insertion time.

before, I want to program rum's internal WAL instead of generic WAL. but it diffcult for me. LOL

joseph
