### ISSUE TITLE
Installation Error: 'stdio.h' file not found (Mac OS Mojave 10.14.6, Postgres 11)

### ISSUE THREAD

**Issue by edyas** [postgrespro/rum#75]
I cannot install rum using the github repository.
https://github.com/postgrespro/rum#using-github-repository

Here is the error when I try to "make USE_PGXS=1":

clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -I. -I./ -I/usr/local/Cellar/postgresql/11.3/include/server -I/usr/local/Cellar/postgresql/11.3/include/internal -I/usr/local/Cellar/icu4c/64.2/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2   -c -o src/rumsort.o src/rumsort.c
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk' [-Wmissing-sysroot]
In file included from src/rumsort.c:18:
In file included from /usr/local/Cellar/postgresql/11.3/include/server/postgres.h:46:
/usr/local/Cellar/postgresql/11.3/include/server/c.h:59:10: fatal error: 
      'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [src/rumsort.o] Error 1

**Comment by Latte-X-sh** [comment]
1 - I encountered the same problem in ubuntu 20.04 and the fix around it was to install postgres-<version> and postgres-server-dev-<version>. example sudo apt install postgress-12 postgres-server-dev-12 (do your equivalent in mac using brew)
2 - After that, (if you have one instance of postgres in your machine) running make USE_PGXS=1 will run as expected since pg_config which prints the config of your latest postgres installed version.
I am assuming you may have two or more instances of postgress hence the pop of that error.In my case, this was the situation and i had to find where pg_config is located (find / -name  'pg_config')
Running that command will take you to /usr/bin/pg_config which you can open with vi or gedit.Inside that file we a variable called PGBINROOT ="usr/lib/postresql/" i changed it to "usr/lib/postgresql" and then i changed the LATEST_SERVER_DEV ="`ls -v $PGBINROOT*/bin/pg_config 2>/dev/null|tail -n1` TO `ls -v $PGBINROOT/12/bin/pg_config 2>/dev/null|tail -n1`. -SO adding the 12 and removing the * will make pg_config to always print configs for postgres 12 ..you can use the version u installed not 12.
3- Finally i run make USE_PGSX=1 and i worked.

REFERENCE LINKS
https://stackoverflow.com/questions/48562616/pg-config-how-to-change-postgres-versions
