### ISSUE TITLE
Support search with similarities? 

### ISSUE THREAD

**Issue by antsmartian** [postgrespro/rum#87]
Hello, 

Thanks for such a nice extension. I wanted to understand, whether I can query a phrasesearch with spelling mistakes? I do see in docs, and other places, `GIN` do support `trigram` , not sure how does the case here for `rum`. 

Is it possible to do so?

**Comment by shtse8** [comment]
> Hello,
> 
> Thanks for such a nice extension. I wanted to understand, whether I can query a phrasesearch with spelling mistakes? I do see in docs, and other places, `GIN` do support `trigram` , not sure how does the case here for `rum`.
> 
> Is it possible to do so?

did you get any answer? I have the same question.

**Comment by sokolcati** [comment]
Hi!

The RUM module provides phrase search, but without the ability to handle typos.

But the good news is that it is compatible with modules created specifically for searching similar phrases (and more successfully than GIN). It turns out that you can index your table with RUM and use the search implemented by the [pg_trgm](https://postgrespro.com/docs/postgresql/17/pgtrgm) module or another.

I found an old but very informative article on this topic: https://habr.com/ru/articles/341142/
